M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-07T21:58:50-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-07T21:58:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.3606Y-4.3894
X4.5881Y-4.3894
M30
